project:
  name: base
  description: Schema Compiler & Signing Infrastructure Template
  license: CC-BY-NC-SA-4.0
  main_branch: main
  owner: Gabor Zoltan Sinko
  maintenance:
    status: active
    supported_until: '2026-12-31'
  contacts:
    - type: email
      value: sgz@centralinfracore.hu
  links:
    - name: repository
      url: https://github.com/CentralInfraCore/base-repo.git
    - name: documentation
      url: /docs
compiler_settings:
  meta_schemas_dir: ./
  meta_schema_file: md.meta.schema.yaml
  vault_key_name: cic-my-sign-key
release:
  version: 0.5.0
  timestamp: '2025-10-18T20:04:37.092582+00:00'
  repository_tree_hash: hW9FeE9LiuQw4fWBYaUfUKPACQFN+D4IvMYvZ04pz7I=
  sign: vault:v1:MEUCIG2CXSZdQ6SUW6qNzfODfRvm0jciOQk2SXDSYUQHDCPtAiEAwmDMIk+1sn/kaMO/pnBs6mNNzqadUvLbKrgcTpSxgKQ=
  cert: "Certificate:\n    Data:\n        Version: 3 (0x2)\n        Serial Number:\
    \ 4097 (0x1001)\n        Signature Algorithm: ecdsa-with-SHA256\n        Issuer:\
    \ C=HU, O=CentralInfraCore, CN=CIC Root CA\n        Validity\n            Not\
    \ Before: Oct 10 20:23:22 2025 GMT\n            Not After : Oct  5 20:23:22 2026\
    \ GMT\n        Subject: C=HU, O=CentralInfraCore, CN=Gabor Zoltan Sinko\n    \
    \    Subject Public Key Info:\n            Public Key Algorithm: id-ecPublicKey\n\
    \                Public-Key: (256 bit)\n                pub:\n               \
    \     04:e8:75:85:c9:5e:cd:2e:fe:b2:b3:dd:4d:2e:b5:\n                    7a:d6:c0:de:5b:77:68:ea:ad:6f:f9:c6:12:b1:e5:\n\
    \                    5b:a2:07:08:54:e0:77:24:33:5f:c6:4a:8a:8d:c4:\n         \
    \           99:8c:cd:68:14:23:00:80:26:43:d5:ff:f6:96:b3:\n                  \
    \  8d:de:b9:6a:56\n                ASN1 OID: prime256v1\n                NIST\
    \ CURVE: P-256\n        X509v3 extensions:\n            X509v3 Basic Constraints:\
    \ \n                CA:FALSE\n            X509v3 Subject Key Identifier: \n  \
    \              18:2B:65:8D:21:54:18:D0:14:DD:15:8D:DB:A7:D3:6A:A4:B3:61:0C\n \
    \           X509v3 Authority Key Identifier: \n                04:AF:7A:55:90:FB:06:56:DD:89:34:F4:1B:B9:37:0A:2C:47:41:09\n\
    \            X509v3 Subject Alternative Name: \n                email:sgz@centralinfracore.hu\n\
    \            X509v3 Key Usage: \n                Digital Signature, Key Encipherment\n\
    \            X509v3 Extended Key Usage: \n                TLS Web Client Authentication\n\
    \    Signature Algorithm: ecdsa-with-SHA256\n    Signature Value:\n        30:44:02:20:50:3a:73:e6:dc:89:a5:63:c4:82:00:ff:18:8c:\n\
    \        6e:dd:1f:9d:2b:ac:36:24:db:9d:e9:4b:67:53:12:d7:f8:90:\n        02:20:21:18:37:fe:3e:6c:54:c2:28:6b:f1:1b:44:6e:93:b8:\n\
    \        a0:b4:f7:8b:42:4d:d5:48:22:af:83:da:5f:0b:2b:16\n-----BEGIN CERTIFICATE-----\n\
    MIICBzCCAa6gAwIBAgICEAEwCgYIKoZIzj0EAwIwPjELMAkGA1UEBhMCSFUxGTAX\nBgNVBAoMEENlbnRyYWxJbmZyYUNvcmUxFDASBgNVBAMMC0NJQyBSb290IENBMB4X\n\
    DTI1MTAxMDIwMjMyMloXDTI2MTAwNTIwMjMyMlowRTELMAkGA1UEBhMCSFUxGTAX\nBgNVBAoMEENlbnRyYWxJbmZyYUNvcmUxGzAZBgNVBAMMEkdhYm9yIFpvbHRhbiBT\n\
    aW5rbzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABOh1hclezS7+srPdTS61etbA\n3lt3aOqtb/nGErHlW6IHCFTgdyQzX8ZKio3EmYzNaBQjAIAmQ9X/9pazjd65alaj\n\
    gZQwgZEwCQYDVR0TBAIwADAdBgNVHQ4EFgQUGCtljSFUGNAU3RWN26fTaqSzYQww\nHwYDVR0jBBgwFoAUBK96VZD7BlbdiTT0G7k3CixHQQkwIgYDVR0RBBswGYEXc2d6\n\
    QGNlbnRyYWxpbmZyYWNvcmUuaHUwCwYDVR0PBAQDAgWgMBMGA1UdJQQMMAoGCCsG\nAQUFBwMCMAoGCCqGSM49BAMCA0cAMEQCIFA6c+bciaVjxIIA/xiMbt0fnSusNiTb\n\
    nelLZ1MS1/iQAiAhGDf+PmxUwihr8RtEbpO4oLT3i0JN1Ugir4PaXwsrFg==\n-----END CERTIFICATE-----"
