---
project:
  name: base
  description: Schema Compiler & Signing Infrastructure Template
  license: CC-BY-NC-SA-4.0
  main_branch: main
  owner: Gabor Zoltan Sinko
  maintenance:
    status: active
    supported_until: '2026-12-31'
  contacts:
    - type: email
      value: sgz@centralinfracore.hu
  links:
    - name: repository
      url: https://github.com/CentralInfraCore/base-repo.git
    - name: documentation
      url: /docs
compiler_settings:
  component_name: base
  meta_schemas_dir: ./
  source_dir: ./
  meta_schema_file: md.meta.schema.yaml
  vault_key_name: cic-my-sign-key
  cic_root_ca_key_name: cic-root-ca-key
  # Added Vault certificate settings
  vault_cert_mount: "cic-my-sign-key"
  vault_cert_secret_name: "crt"
  vault_cert_secret_key: "bar"
